### ISSUE TITLE
Faucet factory can be simplified

### ISSUE THREAD

**Issue by 0xsarvesh** [mosaicdao/faucet#3]
Faucet type can be made an enum kind and switch case can be simplified by binding instantiation with the type of the enum instead of a string.

**Comment by schemar** [comment]
Yes!

Please note the following:
Right now, the chain string is used throughout the project to access the configurations of the individual parts. Thus, this ticket incurs further changes:

* The most outer layer (probably `Server.ts`) should identify the config for each chain.
* Instead of passing chain strings around, the correct chain object from the config should be passed around (only the one of the one relevant chain).
* In *addition* to the config, we need to pass the new faucet type enum value to all methods that require to know the faucet type (*probably* just the `FaucetFactory`).
* Make sure that creating the new account and storing it in the file is still possible within `Accont.ts` without passing the chain name and without direct access to the config. It might be required to extract the method that gets the file name from the config into an upper layer and pass it to the function that creates a new account.

Thoughts @sarvesh-ost ?
